<#
.SYNOPSIS
    myTech.Today RMM - Windows Client Installation Script

.DESCRIPTION
    Lightweight installer for Windows client devices that will be managed by an RMM server.
    This installs only the client agent, not the full administrator interface.

    Installation Paths (Microsoft Best Practices):
    - Program Files: C:\Program Files (x86)\myTech.Today\RMM-Client\
    - Data/Config:   C:\ProgramData\myTech.Today\RMM-Client\

    Features:
    - Installs RMM client agent
    - Provides GUI for entering server URL and pairing code
    - Shows device details (read-only) without administrator controls
    - No credential management capabilities
    - Creates Desktop and Start Menu shortcuts

.PARAMETER ServerUrl
    URL of the RMM server (e.g., http://192.168.1.100:8080)

.PARAMETER PairingCode
    6-character pairing code generated by the administrator

.PARAMETER Silent
    Run installation without prompts (requires ServerUrl and PairingCode)

.EXAMPLE
    .\install-client-windows.ps1
    Runs interactive installation with GUI prompts.

.EXAMPLE
    .\install-client-windows.ps1 -ServerUrl "http://192.168.1.100:8080" -PairingCode "ABC123"
    Automated installation with auto-registration.

.EXAMPLE
    .\install-client-windows.ps1 -Silent -ServerUrl "http://server:8080" -PairingCode "XYZ789"
    Silent installation with no visible output.

.NOTES
    Author: myTech.Today
    Version: 2.0.0
    Requires: Administrator privileges for standard installation
#>

#Requires -Version 5.1

[CmdletBinding()]
param(
    [Parameter()]
    [string]$ServerUrl,

    [Parameter()]
    [string]$PairingCode,

    [Parameter()]
    [switch]$Silent
)

# PowerShell 7+ Version Check - myTech.Today standard
$script:PS7ContinueOnPS51 = $true  # Allow running on PS 5.1 with warning
$script:PS7Silent = $false
$script:_RepoRoot = $PSScriptRoot
while ($script:_RepoRoot -and -not (Test-Path (Join-Path $script:_RepoRoot 'scripts\Require-PowerShell7.ps1'))) {
    $script:_RepoRoot = Split-Path $script:_RepoRoot -Parent
}
if ($script:_RepoRoot -and (Test-Path (Join-Path $script:_RepoRoot 'scripts\Require-PowerShell7.ps1'))) {
    . (Join-Path $script:_RepoRoot 'scripts\Require-PowerShell7.ps1')
}

$ErrorActionPreference = 'Stop'

#region Path Configuration
$ScriptDir = $PSScriptRoot

# Check for admin rights - determines installation mode
$IsAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

if ($IsAdmin) {
    # Standard paths (requires admin)
    $ProgramFilesRoot = "${env:ProgramFiles(x86)}\myTech.Today"
    $RMMClientPath = "$ProgramFilesRoot\RMM-Client"
    $ProgramDataRoot = "$env:ProgramData\myTech.Today\RMM-Client"
    $ConfigPath = "$ProgramDataRoot\config"
    $LogPath = "$ProgramDataRoot\logs"
    $PublicDesktop = "$env:PUBLIC\Desktop"
    $StartMenuFolder = "$env:ProgramData\Microsoft\Windows\Start Menu\Programs\myTech.Today"
} else {
    # User-mode installation (no admin required)
    $RMMClientPath = "$env:LOCALAPPDATA\myTech.Today\RMM-Client"
    $ProgramDataRoot = $RMMClientPath
    $ConfigPath = "$RMMClientPath\config"
    $LogPath = "$RMMClientPath\logs"
    $PublicDesktop = [Environment]::GetFolderPath('Desktop')
    $StartMenuFolder = Join-Path ([Environment]::GetFolderPath('StartMenu')) "Programs\myTech.Today"
}
#endregion

#region Helper Functions
function Show-Banner {
    param([string]$Title, [string]$Color = "Cyan")
    if (-not $Silent) {
        Write-Host ""
        Write-Host ("=" * 50) -ForegroundColor $Color
        Write-Host "  $Title" -ForegroundColor White
        Write-Host ("=" * 50) -ForegroundColor $Color
        Write-Host ""
    }
}

function Write-Step {
    param([string]$Step, [string]$Message)
    if (-not $Silent) {
        Write-Host "[$Step] $Message" -ForegroundColor Yellow
    }
}

function Write-OK {
    param([string]$Message)
    if (-not $Silent) {
        Write-Host "  [OK] $Message" -ForegroundColor Green
    }
}

function Write-Info {
    param([string]$Message)
    if (-not $Silent) {
        Write-Host "  $Message" -ForegroundColor Gray
    }
}

function Write-Fail {
    param([string]$Message)
    if (-not $Silent) {
        Write-Host "  [FAIL] $Message" -ForegroundColor Red
    }
}
#endregion

#region GUI Registration Form
function Show-RegistrationGUI {
    <#
    .SYNOPSIS
        Shows a Windows Forms GUI for entering server URL and pairing code
    #>
    Add-Type -AssemblyName System.Windows.Forms
    Add-Type -AssemblyName System.Drawing

    $form = New-Object System.Windows.Forms.Form
    $form.Text = "myTech.Today RMM - Client Registration"
    $form.Size = New-Object System.Drawing.Size(450, 280)
    $form.StartPosition = "CenterScreen"
    $form.FormBorderStyle = "FixedDialog"
    $form.MaximizeBox = $false
    $form.MinimizeBox = $false
    $form.BackColor = [System.Drawing.Color]::White

    # Title Label
    $titleLabel = New-Object System.Windows.Forms.Label
    $titleLabel.Location = New-Object System.Drawing.Point(20, 15)
    $titleLabel.Size = New-Object System.Drawing.Size(400, 25)
    $titleLabel.Text = "Register this device with RMM Server"
    $titleLabel.Font = New-Object System.Drawing.Font("Segoe UI", 12, [System.Drawing.FontStyle]::Bold)
    $titleLabel.ForeColor = [System.Drawing.Color]::FromArgb(102, 126, 234)
    $form.Controls.Add($titleLabel)

    # Server URL Label
    $serverLabel = New-Object System.Windows.Forms.Label
    $serverLabel.Location = New-Object System.Drawing.Point(20, 55)
    $serverLabel.Size = New-Object System.Drawing.Size(120, 20)
    $serverLabel.Text = "Server URL:"
    $serverLabel.Font = New-Object System.Drawing.Font("Segoe UI", 10)
    $form.Controls.Add($serverLabel)

    # Server URL TextBox
    $serverTextBox = New-Object System.Windows.Forms.TextBox
    $serverTextBox.Location = New-Object System.Drawing.Point(20, 78)
    $serverTextBox.Size = New-Object System.Drawing.Size(390, 25)
    $serverTextBox.Font = New-Object System.Drawing.Font("Segoe UI", 10)
    $serverTextBox.Text = "http://"
    $form.Controls.Add($serverTextBox)

    # Pairing Code Label
    $codeLabel = New-Object System.Windows.Forms.Label
    $codeLabel.Location = New-Object System.Drawing.Point(20, 115)
    $codeLabel.Size = New-Object System.Drawing.Size(200, 20)
    $codeLabel.Text = "6-Character Pairing Code:"
    $codeLabel.Font = New-Object System.Drawing.Font("Segoe UI", 10)
    $form.Controls.Add($codeLabel)

    # Pairing Code TextBox
    $codeTextBox = New-Object System.Windows.Forms.TextBox
    $codeTextBox.Location = New-Object System.Drawing.Point(20, 138)
    $codeTextBox.Size = New-Object System.Drawing.Size(150, 25)
    $codeTextBox.Font = New-Object System.Drawing.Font("Consolas", 14)
    $codeTextBox.MaxLength = 6
    $codeTextBox.CharacterCasing = "Upper"
    $form.Controls.Add($codeTextBox)

    # Status Label
    $statusLabel = New-Object System.Windows.Forms.Label
    $statusLabel.Location = New-Object System.Drawing.Point(20, 175)
    $statusLabel.Size = New-Object System.Drawing.Size(390, 20)
    $statusLabel.Text = ""
    $statusLabel.Font = New-Object System.Drawing.Font("Segoe UI", 9)
    $form.Controls.Add($statusLabel)

    # Register Button
    $registerButton = New-Object System.Windows.Forms.Button
    $registerButton.Location = New-Object System.Drawing.Point(20, 200)
    $registerButton.Size = New-Object System.Drawing.Size(120, 35)
    $registerButton.Text = "Register"
    $registerButton.Font = New-Object System.Drawing.Font("Segoe UI", 10, [System.Drawing.FontStyle]::Bold)
    $registerButton.BackColor = [System.Drawing.Color]::FromArgb(102, 126, 234)
    $registerButton.ForeColor = [System.Drawing.Color]::White
    $registerButton.FlatStyle = "Flat"
    $registerButton.Cursor = "Hand"
    $form.Controls.Add($registerButton)

    # Cancel Button
    $cancelButton = New-Object System.Windows.Forms.Button
    $cancelButton.Location = New-Object System.Drawing.Point(150, 200)
    $cancelButton.Size = New-Object System.Drawing.Size(100, 35)
    $cancelButton.Text = "Cancel"
    $cancelButton.Font = New-Object System.Drawing.Font("Segoe UI", 10)
    $cancelButton.FlatStyle = "Flat"
    $cancelButton.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
    $form.Controls.Add($cancelButton)

    # Result storage
    $script:guiResult = @{ Success = $false; ServerUrl = ""; PairingCode = "" }

    # Register button click handler
    $registerButton.Add_Click({
        $server = $serverTextBox.Text.Trim().TrimEnd('/')
        $code = $codeTextBox.Text.Trim().ToUpper()

        # Validate
        if (-not $server -or $server -eq "http://") {
            $statusLabel.Text = "Please enter a valid server URL"
            $statusLabel.ForeColor = [System.Drawing.Color]::Red
            return
        }
        if (-not $code -or $code.Length -ne 6) {
            $statusLabel.Text = "Pairing code must be exactly 6 characters"
            $statusLabel.ForeColor = [System.Drawing.Color]::Red
            return
        }

        $script:guiResult.Success = $true
        $script:guiResult.ServerUrl = $server
        $script:guiResult.PairingCode = $code
        $form.DialogResult = [System.Windows.Forms.DialogResult]::OK
        $form.Close()
    })

    $form.AcceptButton = $registerButton
    $form.CancelButton = $cancelButton

    # Ensure form appears in center of screen and gets focus
    $form.TopMost = $true
    $form.Add_Shown({
        $this.TopMost = $false  # Allow other windows after shown
        $this.Activate()
        $this.Focus()
    })

    $dialogResult = $form.ShowDialog()

    if ($dialogResult -eq [System.Windows.Forms.DialogResult]::OK) {
        return $script:guiResult
    }
    return $null
}
#endregion

#region Main Installation
Show-Banner "myTech.Today RMM - Windows Client"

if ($IsAdmin) {
    Write-Info "Running with Administrator privileges - using system paths"
} else {
    Write-Info "Running without admin - using user-local paths"
}

Write-Step "1/5" "Creating directory structure..."

# Program Files directories (binaries)
$programDirs = @(
    $RMMClientPath,
    "$RMMClientPath\scripts",
    "$RMMClientPath\scripts\core"
)

# ProgramData directories (writable data)
$dataDirs = @(
    $ProgramDataRoot,
    $ConfigPath,
    $LogPath
)

foreach ($dir in $programDirs) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
}

foreach ($dir in $dataDirs) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
}
Write-OK "Directories created"
Write-Info "  Program: $RMMClientPath"
Write-Info "  Data:    $ProgramDataRoot"

Write-Step "2/5" "Installing RMM Client Agent..."

# Copy or download RMM-Client.ps1
$clientScriptSource = Join-Path $ScriptDir "scripts\core\RMM-Client.ps1"
$clientScriptDest = "$RMMClientPath\scripts\core\RMM-Client.ps1"

if (Test-Path $clientScriptSource) {
    Copy-Item -Path $clientScriptSource -Destination $clientScriptDest -Force
    Write-OK "Client agent installed from local source"
} else {
    # Download from GitHub
    $downloadUrl = "https://raw.githubusercontent.com/mytech-today-now/RMM/main/scripts/core/RMM-Client.ps1"
    try {
        Invoke-WebRequest -Uri $downloadUrl -OutFile $clientScriptDest -UseBasicParsing
        Write-OK "Client agent downloaded from GitHub"
    } catch {
        Write-Fail "Could not download client script: $($_.Exception.Message)"
        Write-Info "Please manually copy RMM-Client.ps1 to: $clientScriptDest"
    }
}

Write-Step "3/5" "Creating convenience scripts..."

# Create a launcher script
$launcherScript = @"
# myTech.Today RMM Client Launcher
# Run this script to register with an RMM server

param(
    [string]`$ServerUrl,
    [string]`$PairingCode,
    [switch]`$Interactive
)

`$clientScript = Join-Path `$PSScriptRoot "scripts\core\RMM-Client.ps1"
& `$clientScript @PSBoundParameters
"@
$launcherScript | Out-File -FilePath "$RMMClientPath\Register-Device.ps1" -Encoding UTF8 -Force
Write-OK "Launcher script created"

Write-Step "4/5" "Creating shortcuts..."

# Helper function to create shortcuts
function New-Shortcut {
    param(
        [string]$ShortcutPath,
        [string]$TargetPath,
        [string]$Arguments,
        [string]$WorkingDirectory,
        [string]$Description
    )
    try {
        $WshShell = New-Object -ComObject WScript.Shell
        $Shortcut = $WshShell.CreateShortcut($ShortcutPath)
        $Shortcut.TargetPath = $TargetPath
        if ($Arguments) { $Shortcut.Arguments = $Arguments }
        if ($WorkingDirectory) { $Shortcut.WorkingDirectory = $WorkingDirectory }
        if ($Description) { $Shortcut.Description = $Description }
        $Shortcut.Save()
        [System.Runtime.Interopservices.Marshal]::ReleaseComObject($WshShell) | Out-Null
        return $true
    } catch {
        return $false
    }
}

# Create Start Menu folder
if (-not (Test-Path $StartMenuFolder)) {
    New-Item -ItemType Directory -Path $StartMenuFolder -Force | Out-Null
}

# Client shortcut - Desktop
$clientDesktopShortcut = Join-Path $PublicDesktop "mTT RMM Client.lnk"
$clientScript = "$RMMClientPath\Register-Device.ps1"
if (New-Shortcut -ShortcutPath $clientDesktopShortcut `
                 -TargetPath "powershell.exe" `
                 -Arguments "-NoProfile -ExecutionPolicy Bypass -File `"$clientScript`" -Interactive" `
                 -WorkingDirectory $RMMClientPath `
                 -Description "myTech.Today RMM Client - Register or manage this device") {
    Write-OK "Desktop shortcut: $clientDesktopShortcut"
} else {
    Write-Info "Could not create desktop shortcut"
}

# Client shortcut - Start Menu
$clientStartMenuShortcut = Join-Path $StartMenuFolder "mTT RMM Client.lnk"
if (New-Shortcut -ShortcutPath $clientStartMenuShortcut `
                 -TargetPath "powershell.exe" `
                 -Arguments "-NoProfile -ExecutionPolicy Bypass -File `"$clientScript`" -Interactive" `
                 -WorkingDirectory $RMMClientPath `
                 -Description "myTech.Today RMM Client - Register or manage this device") {
    Write-OK "Start Menu shortcut: $clientStartMenuShortcut"
}

Write-Step "5/5" "Device Registration..."

# Get registration info (from params, GUI, or skip)
$registrationData = $null

if ($ServerUrl -and $PairingCode) {
    # Use provided parameters
    $registrationData = @{
        Success = $true
        ServerUrl = $ServerUrl.TrimEnd('/')
        PairingCode = $PairingCode.ToUpper()
    }
    Write-Info "Using provided credentials"
} elseif (-not $Silent) {
    # Show GUI for registration
    Write-Info "Opening registration dialog..."
    $registrationData = Show-RegistrationGUI
}

if ($registrationData -and $registrationData.Success) {
    Write-Info "Registering with server: $($registrationData.ServerUrl)"

    # Run the client registration
    $clientArgs = @{
        ServerUrl = $registrationData.ServerUrl
        PairingCode = $registrationData.PairingCode
    }
    if (-not $Silent) {
        $clientArgs.Interactive = $true
    }

    try {
        & $clientScriptDest @clientArgs
        $exitCode = $LASTEXITCODE
        if ($exitCode -eq 0) {
            # Save config for future use
            $config = @{
                ServerUrl = $registrationData.ServerUrl
                RegisteredAt = (Get-Date -Format "o")
                DeviceId = $null  # Will be populated after registration
            }
            $config | ConvertTo-Json | Out-File -FilePath "$ConfigPath\client-config.json" -Encoding UTF8
            Write-OK "Registration successful!"
        }
    } catch {
        Write-Fail "Registration failed: $($_.Exception.Message)"
    }
} else {
    if (-not $Silent) {
        Write-Host ""
        Write-Host "========================================" -ForegroundColor Green
        Write-Host "  Installation Complete!" -ForegroundColor Green
        Write-Host "========================================" -ForegroundColor Green
        Write-Host ""
        Write-Host "Installation Summary:" -ForegroundColor Cyan
        Write-Host "  Program Files: $RMMClientPath" -ForegroundColor Gray
        Write-Host "  Data/Config:   $ProgramDataRoot" -ForegroundColor Gray
        Write-Host "  Desktop:       $clientDesktopShortcut" -ForegroundColor Gray
        Write-Host "  Start Menu:    $StartMenuFolder" -ForegroundColor Gray
        Write-Host ""
        Write-Host "To register this device later:" -ForegroundColor White
        Write-Host "  Double-click 'mTT RMM Client' on your Desktop, or run:" -ForegroundColor Gray
        Write-Host "  & '$RMMClientPath\Register-Device.ps1' -Interactive" -ForegroundColor Yellow
        Write-Host ""
        Write-Host "Your administrator will provide:" -ForegroundColor Gray
        Write-Host "  1. The RMM server URL" -ForegroundColor Gray
        Write-Host "  2. A 6-character pairing code" -ForegroundColor Gray
        Write-Host ""
    }
}
#endregion

#region Client Status Viewer Script
# Create a script that shows device status (read-only, no admin controls)
$clientViewerScript = @'
<#
.SYNOPSIS
    myTech.Today RMM - Client Device Viewer

.DESCRIPTION
    Read-only viewer for the current device's status in the RMM system.
    Shows device details without administrator controls or credential management.

.NOTES
    This is a client-only view - no administrative functions are available.
#>

param([switch]$Refresh)

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$configPath = Join-Path $PSScriptRoot "config\client-config.json"

function Get-DeviceStatus {
    param([string]$ServerUrl, [string]$DeviceId)

    if (-not $ServerUrl -or -not $DeviceId) { return $null }

    try {
        $response = Invoke-RestMethod -Uri "$ServerUrl/api/devices/$DeviceId" -Method Get -TimeoutSec 10
        return $response
    } catch {
        return $null
    }
}

function Get-LocalDeviceInfo {
    $info = @{
        Hostname = $env:COMPUTERNAME
        IPAddress = $null
        OSName = $null
        OSVersion = $null
        DeviceType = "Workstation"
    }

    try {
        $ip = Get-NetIPAddress -AddressFamily IPv4 |
              Where-Object { $_.IPAddress -notmatch '^(127\.|169\.254\.)' } |
              Select-Object -First 1
        $info.IPAddress = $ip.IPAddress
    } catch { }

    try {
        $os = Get-CimInstance Win32_OperatingSystem
        $info.OSName = $os.Caption
        $info.OSVersion = $os.Version
    } catch { }

    return $info
}

# Create main form
$form = New-Object System.Windows.Forms.Form
$form.Text = "myTech.Today RMM - Device Status"
$form.Size = New-Object System.Drawing.Size(500, 450)
$form.StartPosition = "CenterScreen"
$form.FormBorderStyle = "FixedDialog"
$form.MaximizeBox = $false
$form.BackColor = [System.Drawing.Color]::White

# Title
$titleLabel = New-Object System.Windows.Forms.Label
$titleLabel.Location = New-Object System.Drawing.Point(20, 15)
$titleLabel.Size = New-Object System.Drawing.Size(450, 30)
$titleLabel.Text = "Device Status"
$titleLabel.Font = New-Object System.Drawing.Font("Segoe UI", 14, [System.Drawing.FontStyle]::Bold)
$titleLabel.ForeColor = [System.Drawing.Color]::FromArgb(102, 126, 234)
$form.Controls.Add($titleLabel)

# Device info panel
$infoPanel = New-Object System.Windows.Forms.Panel
$infoPanel.Location = New-Object System.Drawing.Point(20, 55)
$infoPanel.Size = New-Object System.Drawing.Size(445, 300)
$infoPanel.BorderStyle = "FixedSingle"
$form.Controls.Add($infoPanel)

# Get local device info
$localInfo = Get-LocalDeviceInfo

# Load config and get server status
$serverInfo = $null
$isRegistered = $false
if (Test-Path $configPath) {
    $config = Get-Content $configPath | ConvertFrom-Json
    if ($config.ServerUrl -and $config.DeviceId) {
        $serverInfo = Get-DeviceStatus -ServerUrl $config.ServerUrl -DeviceId $config.DeviceId
        $isRegistered = $true
    }
}

# Create info labels
$yPos = 10
$fields = @(
    @{ Label = "Hostname"; Value = $localInfo.Hostname.ToUpper() },
    @{ Label = "IP Address"; Value = $localInfo.IPAddress },
    @{ Label = "Operating System"; Value = $localInfo.OSName },
    @{ Label = "OS Version"; Value = $localInfo.OSVersion },
    @{ Label = "Device Type"; Value = $localInfo.DeviceType },
    @{ Label = "Registration Status"; Value = if ($isRegistered) { "Registered" } else { "Not Registered" } }
)

if ($serverInfo) {
    $fields += @(
        @{ Label = "RMM Status"; Value = $serverInfo.status },
        @{ Label = "Last Seen"; Value = $serverInfo.lastSeen },
        @{ Label = "Site"; Value = $serverInfo.siteName }
    )
}

foreach ($field in $fields) {
    $labelCtrl = New-Object System.Windows.Forms.Label
    $labelCtrl.Location = New-Object System.Drawing.Point(10, $yPos)
    $labelCtrl.Size = New-Object System.Drawing.Size(140, 25)
    $labelCtrl.Text = "$($field.Label):"
    $labelCtrl.Font = New-Object System.Drawing.Font("Segoe UI", 10, [System.Drawing.FontStyle]::Bold)
    $infoPanel.Controls.Add($labelCtrl)

    $valueCtrl = New-Object System.Windows.Forms.Label
    $valueCtrl.Location = New-Object System.Drawing.Point(155, $yPos)
    $valueCtrl.Size = New-Object System.Drawing.Size(275, 25)
    $valueCtrl.Text = if ($field.Value) { $field.Value } else { "N/A" }
    $valueCtrl.Font = New-Object System.Drawing.Font("Segoe UI", 10)

    # Color code status
    if ($field.Label -eq "Registration Status") {
        $valueCtrl.ForeColor = if ($isRegistered) { [System.Drawing.Color]::Green } else { [System.Drawing.Color]::Orange }
    }
    if ($field.Label -eq "RMM Status") {
        $valueCtrl.ForeColor = switch ($field.Value) {
            "Online" { [System.Drawing.Color]::Green }
            "Offline" { [System.Drawing.Color]::Red }
            default { [System.Drawing.Color]::Gray }
        }
    }

    $infoPanel.Controls.Add($valueCtrl)
    $yPos += 28
}

# Refresh button
$refreshBtn = New-Object System.Windows.Forms.Button
$refreshBtn.Location = New-Object System.Drawing.Point(20, 365)
$refreshBtn.Size = New-Object System.Drawing.Size(100, 35)
$refreshBtn.Text = "Refresh"
$refreshBtn.Font = New-Object System.Drawing.Font("Segoe UI", 10)
$refreshBtn.BackColor = [System.Drawing.Color]::FromArgb(102, 126, 234)
$refreshBtn.ForeColor = [System.Drawing.Color]::White
$refreshBtn.FlatStyle = "Flat"
$refreshBtn.Add_Click({
    $form.Close()
    & $MyInvocation.MyCommand.Path -Refresh
})
$form.Controls.Add($refreshBtn)

# Close button
$closeBtn = New-Object System.Windows.Forms.Button
$closeBtn.Location = New-Object System.Drawing.Point(130, 365)
$closeBtn.Size = New-Object System.Drawing.Size(100, 35)
$closeBtn.Text = "Close"
$closeBtn.Font = New-Object System.Drawing.Font("Segoe UI", 10)
$closeBtn.FlatStyle = "Flat"
$closeBtn.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
$form.Controls.Add($closeBtn)

# Note about no admin access
$noteLabel = New-Object System.Windows.Forms.Label
$noteLabel.Location = New-Object System.Drawing.Point(250, 375)
$noteLabel.Size = New-Object System.Drawing.Size(230, 20)
$noteLabel.Text = "Read-only view - Contact your administrator"
$noteLabel.Font = New-Object System.Drawing.Font("Segoe UI", 8, [System.Drawing.FontStyle]::Italic)
$noteLabel.ForeColor = [System.Drawing.Color]::Gray
$form.Controls.Add($noteLabel)

$form.ShowDialog() | Out-Null
'@

$clientViewerScript | Out-File -FilePath "$RMMClientPath\View-DeviceStatus.ps1" -Encoding UTF8 -Force

# Create desktop shortcut for the viewer
try {
    $WshShell = New-Object -ComObject WScript.Shell
    $desktopPath = [Environment]::GetFolderPath('Desktop')
    $shortcutPath = Join-Path $desktopPath "RMM Client Status.lnk"
    $shortcut = $WshShell.CreateShortcut($shortcutPath)
    $shortcut.TargetPath = "powershell.exe"
    $shortcut.Arguments = "-NoProfile -ExecutionPolicy Bypass -File `"$RMMClientPath\View-DeviceStatus.ps1`""
    $shortcut.WorkingDirectory = $RMMClientPath
    $shortcut.IconLocation = "shell32.dll,15"
    $shortcut.Description = "View device status in myTech.Today RMM"
    $shortcut.Save()
    Write-OK "Desktop shortcut created: RMM Client Status"
} catch {
    Write-Info "Could not create desktop shortcut"
}
#endregion

