<#
.SYNOPSIS
    RMM Client Agent for device registration and monitoring

.DESCRIPTION
    Cross-platform client agent that:
    1. Accepts a pairing code from the RMM administrator
    2. Registers the device with the RMM server
    3. Reports device information (hostname, IP, OS, device type)
    4. Enables remote monitoring and management

    By default, runs silently with no visible output (for background/automated use).
    Use -Interactive flag to show progress and prompts.

.PARAMETER ServerUrl
    URL of the RMM server (e.g., http://192.168.1.100:8080)

.PARAMETER PairingCode
    6-character pairing code generated by the administrator

.PARAMETER Interactive
    Run in interactive mode with visible output and prompts for input

.PARAMETER Silent
    Explicitly run in silent mode (default behavior, provided for clarity)

.EXAMPLE
    .\RMM-Client.ps1 -ServerUrl "http://192.168.1.100:8080" -PairingCode "ABC123"
    Registers silently without visible output.

.EXAMPLE
    .\RMM-Client.ps1 -Interactive
    Shows prompts and progress output.

.EXAMPLE
    .\RMM-Client.ps1 -ServerUrl "http://server:8080" -PairingCode "ABC123" -Interactive
    Registers with visible progress output.

.NOTES
    Author: myTech.Today
    Version: 1.1.0
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$ServerUrl,

    [Parameter()]
    [string]$PairingCode,

    [Parameter()]
    [switch]$Interactive,

    [Parameter()]
    [switch]$Silent
)

#region Helper Functions

function Get-DeviceInfo {
    <#
    .SYNOPSIS
        Collects device information for registration
    #>
    $info = @{
        Hostname  = $env:COMPUTERNAME
        IPAddress = $null
        OSName    = $null
        OSVersion = $null
        DeviceType = "Workstation"
        Manufacturer = $null
        Model = $null
        SerialNumber = $null
    }

    # Get IP Address
    try {
        $ip = Get-NetIPAddress -AddressFamily IPv4 | 
              Where-Object { $_.IPAddress -notmatch '^(127\.|169\.254\.)' } | 
              Select-Object -First 1
        $info.IPAddress = $ip.IPAddress
    } catch {
        # Fallback for non-Windows or older systems
        try {
            $ip = [System.Net.Dns]::GetHostAddresses($env:COMPUTERNAME) | 
                  Where-Object { $_.AddressFamily -eq 'InterNetwork' } | 
                  Select-Object -First 1
            $info.IPAddress = $ip.IPAddressToString
        } catch { }
    }

    # Get OS Information
    if ($IsWindows -or $env:OS -match 'Windows') {
        $os = Get-CimInstance Win32_OperatingSystem -ErrorAction SilentlyContinue
        if ($os) {
            $info.OSName = $os.Caption
            $info.OSVersion = $os.Version
        }

        # Get hardware info
        $cs = Get-CimInstance Win32_ComputerSystem -ErrorAction SilentlyContinue
        if ($cs) {
            $info.Manufacturer = $cs.Manufacturer
            $info.Model = $cs.Model
            
            # Determine device type
            switch ($cs.PCSystemType) {
                1 { $info.DeviceType = "Desktop" }
                2 { $info.DeviceType = "Laptop" }
                3 { $info.DeviceType = "Workstation" }
                4 { $info.DeviceType = "Server" }
                5 { $info.DeviceType = "Server" }
                default { $info.DeviceType = "Workstation" }
            }
            
            # Check if virtual
            if ($cs.Model -match 'Virtual|VMware|Hyper-V|VirtualBox|QEMU') {
                $info.DeviceType = "Virtual"
            }
        }

        $bios = Get-CimInstance Win32_BIOS -ErrorAction SilentlyContinue
        if ($bios) {
            $info.SerialNumber = $bios.SerialNumber
        }
    }
    elseif ($IsMacOS) {
        $info.OSName = "macOS"
        $info.OSVersion = (sw_vers -productVersion 2>$null) -join ''
        $info.DeviceType = "Laptop"  # Most Macs are laptops
        $info.Manufacturer = "Apple"
        $info.Model = (sysctl -n hw.model 2>$null) -join ''
        $info.SerialNumber = (system_profiler SPHardwareDataType 2>$null | 
                              Select-String 'Serial Number' | 
                              ForEach-Object { ($_ -split ':')[1].Trim() }) -join ''
    }
    elseif ($IsLinux) {
        $info.OSName = "Linux"
        if (Test-Path /etc/os-release) {
            $osRelease = Get-Content /etc/os-release | ConvertFrom-StringData -ErrorAction SilentlyContinue
            $info.OSName = $osRelease.PRETTY_NAME -replace '"', ''
        }
        $info.OSVersion = (uname -r 2>$null) -join ''
        $info.DeviceType = "Workstation"
    }

    return $info
}

function Register-WithServer {
    param(
        [string]$Url,
        [string]$Code,
        [hashtable]$DeviceInfo
    )

    $endpoint = "$Url/api/pairing/register"
    
    $body = @{
        pairingCode = $Code
        hostname    = $DeviceInfo.Hostname
        ipAddress   = $DeviceInfo.IPAddress
        osName      = $DeviceInfo.OSName
        osVersion   = $DeviceInfo.OSVersion
        deviceType  = $DeviceInfo.DeviceType
        manufacturer = $DeviceInfo.Manufacturer
        model       = $DeviceInfo.Model
        serialNumber = $DeviceInfo.SerialNumber
    } | ConvertTo-Json

    try {
        $response = Invoke-RestMethod -Uri $endpoint -Method Post -Body $body -ContentType 'application/json' -TimeoutSec 30
        return $response
    } catch {
        return @{ success = $false; error = $_.Exception.Message }
    }
}

#endregion

#region Helper for Output

function Write-ClientOutput {
    param(
        [string]$Message,
        [string]$ForegroundColor = 'White'
    )
    if ($Interactive) {
        Write-Host $Message -ForegroundColor $ForegroundColor
    }
}

#endregion

#region Main Execution

# Only show banner in interactive mode
if ($Interactive) {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host "  myTech.Today RMM Client Agent" -ForegroundColor Cyan
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host ""
}

# Interactive mode - prompt for inputs if not provided
if ($Interactive -and (-not $ServerUrl -or -not $PairingCode)) {
    if (-not $ServerUrl) {
        Write-Host "Enter the RMM Server URL" -ForegroundColor Yellow
        Write-Host "(e.g., http://192.168.1.100:8080)" -ForegroundColor Gray
        $ServerUrl = Read-Host "Server URL"
    }

    if (-not $PairingCode) {
        Write-Host ""
        Write-Host "Enter the 6-character pairing code from your administrator" -ForegroundColor Yellow
        $PairingCode = Read-Host "Pairing Code"
    }
}

# Validate inputs - always check but only output in interactive mode
if (-not $ServerUrl) {
    if ($Interactive) {
        Write-Host "[ERROR] Server URL is required" -ForegroundColor Red
    }
    exit 1
}

if (-not $PairingCode -or $PairingCode.Length -ne 6) {
    if ($Interactive) {
        Write-Host "[ERROR] A valid 6-character pairing code is required" -ForegroundColor Red
    }
    exit 1
}

# Normalize inputs
$ServerUrl = $ServerUrl.TrimEnd('/')
$PairingCode = $PairingCode.ToUpper()

Write-ClientOutput "[1/3] Collecting device information..." -ForegroundColor Cyan
$deviceInfo = Get-DeviceInfo

Write-ClientOutput "      Hostname:    $($deviceInfo.Hostname)" -ForegroundColor Gray
Write-ClientOutput "      IP Address:  $($deviceInfo.IPAddress)" -ForegroundColor Gray
Write-ClientOutput "      OS:          $($deviceInfo.OSName) $($deviceInfo.OSVersion)" -ForegroundColor Gray
Write-ClientOutput "      Device Type: $($deviceInfo.DeviceType)" -ForegroundColor Gray
Write-ClientOutput "" -ForegroundColor White

Write-ClientOutput "[2/3] Connecting to RMM server..." -ForegroundColor Cyan
Write-ClientOutput "      Server: $ServerUrl" -ForegroundColor Gray
Write-ClientOutput "      Code:   $PairingCode" -ForegroundColor Gray
Write-ClientOutput "" -ForegroundColor White

Write-ClientOutput "[3/3] Registering device..." -ForegroundColor Cyan

$result = Register-WithServer -Url $ServerUrl -Code $PairingCode -DeviceInfo $deviceInfo

if ($result.success) {
    if ($Interactive) {
        Write-Host ""
        Write-Host "========================================" -ForegroundColor Green
        Write-Host "  Registration Successful!" -ForegroundColor Green
        Write-Host "========================================" -ForegroundColor Green
        Write-Host ""
        Write-Host "Device ID: $($result.deviceId)" -ForegroundColor White
        Write-Host ""
        Write-Host "Your device has been registered with the RMM server." -ForegroundColor Gray
        Write-Host "The administrator can now monitor and manage this device." -ForegroundColor Gray
        Write-Host ""
    }
    exit 0
} else {
    if ($Interactive) {
        Write-Host ""
        Write-Host "========================================" -ForegroundColor Red
        Write-Host "  Registration Failed" -ForegroundColor Red
        Write-Host "========================================" -ForegroundColor Red
        Write-Host ""
        Write-Host "Error: $($result.error)" -ForegroundColor Yellow
        Write-Host ""
        Write-Host "Please check:" -ForegroundColor Gray
        Write-Host "  - The server URL is correct and accessible" -ForegroundColor Gray
        Write-Host "  - The pairing code is valid and not expired" -ForegroundColor Gray
        Write-Host "  - The RMM server is running" -ForegroundColor Gray
        Write-Host ""
    }
    exit 1
}

#endregion

